import Header from "../../components/layout/Header";
import Footer from "../../components/layout/Footer";
import styles from '../../styles/Home.module.css'
import Head from 'next/head'

export default function SignupPage() {
  return (
    <div>
      <Header />
      <Head>
        <title>Signup page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Signup Page
        </h1>
      </main>
      <Footer />
    </div>
  )
}
